version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - .env
    command: -c "shared_preload_libraries=pg_idkit"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
